spring:
  application:
    name: shop_orders
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/hyperlocal_platform}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Rajnishks@88}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    url: ${FLYWAY_URL:${DB_URL:jdbc:mysql://localhost:3306/hyperlocal_platform}}
    user: ${FLYWAY_USER:${DB_USERNAME:root}}
    password: ${FLYWAY_PASSWORD:${DB_PASSWORD:Rajnishks@88}}

server:
  port: ${SERVER_PORT:8083}
